### ISSUE TITLE
Add file icons and folder icons for modules, services/interceptors, pipes and guards for Angular

### ISSUE THREAD

**Issue by webIllusion95** [catppuccin/vscode-icons#173]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

It would be great to have different Typescript filetype icons. Here's a list of filetype that could benefit from having a related icon:

- file.pipe.ts
- file.guard.ts
- file.module.ts
- file.service.ts
- file.interceptor.ts

### References

<img width="116" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/101396793/d3286203-bc62-40b9-91cf-887e92c753d1">

The image above is just a hint, since a more creative differentiation in shape and colour could lead to a more aesthetically pleasant result.

**Comment by prazdevs** [comment]
hi, since not everyone uses angular and it may seem weird to have angular icons to appear for lets sasy a Nestjs project (they use service/modulez too). These icons exist but are not associated yet.

You need to create custom associations with the extension config, smth like this:

```json
  "catppuccin-icons.associations.extensions": {
    "component.ts": "angular-component",
    "directive.ts": "angular-directive",
    "guard.ts": "angular-guard",
    "pipe.ts": "angular-pipe",
    "service.ts": "angular-service",
    "module.ts": "angular",
  },
```

feel free to reopen if needed :)
