### ISSUE TITLE
[Question] Does the latest version contain icons from my work?

### ISSUE THREAD

**Issue by thang-nm** [catppuccin/vscode-icons#78]
My icons: [Catppuccin-Perfect-Icons](https://github.com/thang-nm/Catppuccin-Perfect-Icons)

**Comment by prazdevs** [comment]
Hi :)

When doing v1, I reworked all the icons, and learnt from your work that 16*16 icons work better (since vsc rasterizes to 32*32). I also took some icons we didn't have and reworked them to better fit the set of guidelines. Besides icons, I reworked a lot of the extension code to include customization through VSCode's API (we now have the first customization feature available!)

I'd have loved to have you contribute upstream to the main repository, you're still welcome to do it!

It was an oversight not including copyright/license notice, I didn't see it as a necessity since the fork was originally based on what I did and edited, I shall raise a PR for it to address LICENSE and thanks section.

Also this repositry aims to become an icon only repo (the extension-related code will be moved to a separate repo), and will probably be much more explicit about licensing (some language/company icons being based on proprietary/licensed things), see [simple-icons](https://github.com/simple-icons/simple-icons) as example.

 Thanks for being understanding. :relieved:

**Comment by thang-nm** [comment]
After spending time recreating over 300 icons from version 0.21.0, I added many more icons. I spent a lot of time finding ideas, as well as how to make them display well on non-retina screens, so I would be very happy if you could add to LICENSE and thanks section as you sad.
Thank you so much 🎉

**Comment by prazdevs** [comment]
done! 😄 

feel free to contribute to the main repo :)
